name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install pytest
        run: pip install pytest

      - name: Check for tests
        run: |
          if ! ls tests/test_*.py 1> /dev/null 2>&1; then
            echo "No test files found matching the pattern 'tests/test_*.py'";
            exit 1;
          fi

      - name: Run tests
        run: pytest tests/

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
